version: '3'

vars:
  # K3d configuration
  K3D_CLUSTER_NAME: testcluster
  LOCAL_IMAGE_REGISTRY_URI: localregistry.localhost
  LOCAL_IMAGE_REGISTRY_PORT: 12345

  APP_NAME: role-controller

tasks:
  default:
    cmds:
      - task help
    silent: true

  help:
    cmds:
      - echo "Welcome to my project - maintainer<Tommy Tran Duc Thang> - email<tommytran.dev@gmail.com>"
      - echo ""
      - echo "Run task <task_name> to run predefined script"
      - echo "Note":" commands start with local":" are for local development"
      - echo ""
      - echo "For install dev environment   task local:install"
      - echo "Going into dev environment    task local:shell"
      - echo ""
      - echo "For running ci on pipeline    task ci:execute but if running it from local make sure you run task:shell first"
      - echo ""
      - task -l
    silent: true

  local:install:
    desc: install required tools, setup env for macOS and Ubuntu
    cmds:
      - command -v devbox &> /dev/null || { curl -fsSL https://get.jetify.com/devbox | bash; }
      - devbox install 
    silent: true

  local:shell:
    desc: Getting into dev shell that has all required tools for development
    cmds:
      - |
        if [ "$DEVBOX_SHELL_ENABLED" != "1" ]; then
          echo "Going into devbox shell"
          devbox shell
        fi
      - echo "You already in devbox shell"
    silent: true

  local:shell:check:
    desc: Getting into dev shell that has all required tools for development
    cmds:
      - |
        if [ "$DEVBOX_SHELL_ENABLED" != "1" ]; then
          echo "You are not in devbox shell. Please go into a devbox shell first by running:"
          echo "task local:shell"
          exit 1; 
        fi
    silent: true
    internal: true

  format:
    desc: Getting into dev shell that has all required tools for development
    cmds:
      - yarn run format 
    silent: true

  kiki:
    desc: (Easter Egg)
    cmds:
      - echo "I love you my kiki Dayeon :3"
    silent: true
